version: "3.7"

services:
  # ----
  # Django API
  django:
    image: app-microservice
    build:
      context: .
      args:
        pipenv_dev: --dev
    volumes:
      - ./app_microservice:/app/app_microservice
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      PYTHONDONTWRITEBYTECODE: "true"
      DJANGO_SECRET_KEY: "ZjYyMjg0YmE0OTJkNjBhNDIyZDkyOTZkN2ZlZWI2ZmFhNDA0NmJmMDAzNmEwYTU2Cg=="
      DJANGO_ACCESS_TOKEN_LIFETIME: 1440 # 1 day (in minutes)
      DJANGO_DEBUG: "True"
      DJANGO_ENVIRONMENT: "local"
      DJANGO_DATABASE_NAME: "app_microservice_dev"
      DJANGO_DATABASE_USER: "root"
      DJANGO_DATABASE_PASSWORD: "devpass"
      DJANGO_DATABASE_HOST: "db"
      DJANGO_DATABASE_PORT: 3306
      GCP_PROJECT_ID: "vet-shelter"
      GCP_BUCKET: "app-media-bucket"
      GOOGLE_OAUTH_AUDIENCE: "481332583913-cieg25daahj0ujclj002o0ei5der0rsi.apps.googleusercontent.com"
      RECOMMENDER_BOT_TOKEN: "NTZiYWU4YjE1ZmQyYzdlMGViZDI1Y2EzODMzZTUxZjQK"
      RECOMMENDER_BOT_TOPIC: "newOffer"
      STORAGE_EMULATOR_HOST: "http://gcp-storage:8080"
    command: --reload --log-level=info

  # ----
  # MySQL Database
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "devpass"
      MYSQL_DATABASE: "app_microservice_dev"
    expose:
      - 3306

  # ----
  # Google Cloud Storage
  gcp-storage:
    image: fsouza/fake-gcs-server
    expose:
      - 8080
    command: -scheme http -port 8080
