version: "3.7"

services:
  # ----
  # Django API
  django:
    image: app-microservice
    build:
      context: .
      args:
        pipenv_dev: --dev
    volumes:
      - ./app_microservice:/app/app_microservice
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      PYTHONDONTWRITEBYTECODE: "true"
      DJANGO_ENVIRONMENT: local
      DJANGO_DATABASE_NAME: app_microservice_dev
      DJANGO_DATABASE_USER: root
      DJANGO_DATABASE_PASSWORD: devpass
      DJANGO_DATABASE_HOST: db
      DJANGO_DATABASE_PORT: 3306
    command: --reload --log-level=info

  # ----
  # MySQL Database
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: app_microservice_dev
    expose:
      - 3306
