# Generated by Django 3.1.5 on 2021-01-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('species', models.CharField(max_length=60)),
                ('breed', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('date_published', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date_created', models.DateField()),
                ('offers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infrastructure.offer')),
            ],
        ),
    ]
