# Generated by Django 3.0.12 on 2021-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='offerimage',
            unique_together={('offer', 'name')},
        ),
    ]
