# Generated by Django 3.0.12 on 2021-02-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210128_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsuser',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
