# Generated by Django 3.0.12 on 2021-02-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210210_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='offers',
            new_name='offer',
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='breed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='place',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='species',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='breed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wsuser',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wsuser',
            name='externalId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wsuser',
            name='profileImageName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wsuser',
            name='signUpMethod',
            field=models.CharField(max_length=255),
        ),
    ]
