# Generated by Django 3.0.12 on 2021-02-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210214_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
