# Generated by Django 3.0.12 on 2021-02-13 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210212_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='media',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='breed',
            field=models.CharField(choices=[('Jack Russel', 'Jack Russel'), ('Persian', 'Persian'), ('White Shark', 'White Shark'), ('Kawuk', 'Kawuk')], max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='species',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Shark', 'Shark'), ('Dinosaur', 'Dinosaur')], max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
