# Generated by Django 3.0.12 on 2021-02-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210214_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='breed',
            field=models.CharField(choices=[('Jack Russel', 'Jack Russel'), ('Persian', 'Persian'), ('White Shark', 'White Shark'), ('Kawuk', 'Kawuk'), ('Chicken', 'Chicken'), ('Lion', 'Lion'), ('Black Widow', 'Black Widow'), ('Owl', 'Owl'), ('Domestic Cat', 'Domestic Cat'), ('Wolf', 'Wolf'), ('Malteser', 'Malteser'), ('English Cocker Spaniel', 'English Cocker Spaniel')], max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='species',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Shark', 'Shark'), ('Dinosaur', 'Dinosaur'), ('Bird', 'Bird'), ('Spider', 'Spider')], max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='breed',
            field=models.CharField(choices=[('Jack Russel', 'Jack Russel'), ('Persian', 'Persian'), ('White Shark', 'White Shark'), ('Kawuk', 'Kawuk'), ('Chicken', 'Chicken'), ('Lion', 'Lion'), ('Black Widow', 'Black Widow'), ('Owl', 'Owl'), ('Domestic Cat', 'Domestic Cat'), ('Wolf', 'Wolf'), ('Malteser', 'Malteser'), ('English Cocker Spaniel', 'English Cocker Spaniel')], max_length=255),
        ),
    ]
