# Generated by Django 3.0.12 on 2021-02-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210214_1214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'breed')},
        ),
    ]
