# Generated by Django 3.0.12 on 2021-02-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210214_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='place',
        ),
        migrations.AddField(
            model_name='offer',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
