# Generated by Django 3.0.12 on 2021-02-08 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wsuser_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
