# Generated by Django 3.0.12 on 2021-02-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210214_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='breed',
            field=models.CharField(choices=[('Jack Russel', 'Jack Russel'), ('Wolf', 'Wolf'), ('Malteser', 'Malteser'), ('English Cocker Spaniel', 'English Cocker Spaniel'), ('Domestic Cat', 'Domestic Cat'), ('Persian', 'Persian'), ('Lion', 'Lion'), ('White Shark', 'White Shark'), ('Kawuk', 'Kawuk'), ('Chicken', 'Chicken'), ('Owl', 'Owl'), ('Black Widow', 'Black Widow')], max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='breed',
            field=models.CharField(choices=[('Jack Russel', 'Jack Russel'), ('Wolf', 'Wolf'), ('Malteser', 'Malteser'), ('English Cocker Spaniel', 'English Cocker Spaniel'), ('Domestic Cat', 'Domestic Cat'), ('Persian', 'Persian'), ('Lion', 'Lion'), ('White Shark', 'White Shark'), ('Kawuk', 'Kawuk'), ('Chicken', 'Chicken'), ('Owl', 'Owl'), ('Black Widow', 'Black Widow')], max_length=255),
        ),
    ]
