# Generated by Django 3.0.12 on 2021-02-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210208_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={},
        ),
    ]
